package entity;
// Generated Apr 30, 2018 11:35:56 PM by Hibernate Tools 4.3.1



/**
 * Acde generated by hbm2java
 */
public class Acde  implements java.io.Serializable {


     private Integer id;
     private String institute;
     private String grp;
     private String major;
     private String result;
     private String respub;
     private String duration;

    public Acde() {
    }

    public Acde(String institute, String grp, String major, String result, String respub, String duration) {
       this.institute = institute;
       this.grp = grp;
       this.major = major;
       this.result = result;
       this.respub = respub;
       this.duration = duration;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(String institute) {
        this.institute = institute;
    }
    public String getGrp() {
        return this.grp;
    }
    
    public void setGrp(String grp) {
        this.grp = grp;
    }
    public String getMajor() {
        return this.major;
    }
    
    public void setMajor(String major) {
        this.major = major;
    }
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    public String getRespub() {
        return this.respub;
    }
    
    public void setRespub(String respub) {
        this.respub = respub;
    }
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }




}


