package entity;
// Generated Apr 30, 2018 11:35:56 PM by Hibernate Tools 4.3.1



/**
 * Bankac generated by hbm2java
 */
public class Bankac  implements java.io.Serializable {


     private Integer id;
     private String bank;
     private String accnum;
     private String branch;

    public Bankac() {
    }

    public Bankac(String bank, String accnum, String branch) {
       this.bank = bank;
       this.accnum = accnum;
       this.branch = branch;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }
    public String getAccnum() {
        return this.accnum;
    }
    
    public void setAccnum(String accnum) {
        this.accnum = accnum;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }




}


