package entity;
// Generated Apr 30, 2018 11:35:56 PM by Hibernate Tools 4.3.1



/**
 * Cv generated by hbm2java
 */
public class Cv  implements java.io.Serializable {


     private Integer id;
     private String a;
     private String b;
     private String c;
     private String d;
     private String e;
     private String f;

    public Cv() {
    }

    public Cv(String a, String b, String c, String d, String e, String f) {
       this.a = a;
       this.b = b;
       this.c = c;
       this.d = d;
       this.e = e;
       this.f = f;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getA() {
        return this.a;
    }
    
    public void setA(String a) {
        this.a = a;
    }
    public String getB() {
        return this.b;
    }
    
    public void setB(String b) {
        this.b = b;
    }
    public String getC() {
        return this.c;
    }
    
    public void setC(String c) {
        this.c = c;
    }
    public String getD() {
        return this.d;
    }
    
    public void setD(String d) {
        this.d = d;
    }
    public String getE() {
        return this.e;
    }
    
    public void setE(String e) {
        this.e = e;
    }
    public String getF() {
        return this.f;
    }
    
    public void setF(String f) {
        this.f = f;
    }




}


