package entity;
// Generated Apr 30, 2018 11:35:56 PM by Hibernate Tools 4.3.1



/**
 * Editpd generated by hbm2java
 */
public class Editpd  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String fname;
     private String mname;
     private String dob;
     private String nid;
     private String nationality;
     private String gen;
     private String religion;
     private String phone;
     private String add;

    public Editpd() {
    }

	
    public Editpd(String name, String email, String fname, String mname, String dob, String nid, String nationality, String gen, String religion, String add) {
        this.name = name;
        this.email = email;
        this.fname = fname;
        this.mname = mname;
        this.dob = dob;
        this.nid = nid;
        this.nationality = nationality;
        this.gen = gen;
        this.religion = religion;
        this.add = add;
    }
    public Editpd(String name, String email, String fname, String mname, String dob, String nid, String nationality, String gen, String religion, String phone, String add) {
       this.name = name;
       this.email = email;
       this.fname = fname;
       this.mname = mname;
       this.dob = dob;
       this.nid = nid;
       this.nationality = nationality;
       this.gen = gen;
       this.religion = religion;
       this.phone = phone;
       this.add = add;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public String getNid() {
        return this.nid;
    }
    
    public void setNid(String nid) {
        this.nid = nid;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public String getGen() {
        return this.gen;
    }
    
    public void setGen(String gen) {
        this.gen = gen;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAdd() {
        return this.add;
    }
    
    public void setAdd(String add) {
        this.add = add;
    }




}


