package entity;
// Generated Apr 30, 2018 11:35:56 PM by Hibernate Tools 4.3.1



/**
 * Monthr generated by hbm2java
 */
public class Monthr  implements java.io.Serializable {


     private Integer sl;
     private String edate;
     private String des;
     private String eve;
     private String statust;

    public Monthr() {
    }

    public Monthr(String edate, String des, String eve, String statust) {
       this.edate = edate;
       this.des = des;
       this.eve = eve;
       this.statust = statust;
    }
   
    public Integer getSl() {
        return this.sl;
    }
    
    public void setSl(Integer sl) {
        this.sl = sl;
    }
    public String getEdate() {
        return this.edate;
    }
    
    public void setEdate(String edate) {
        this.edate = edate;
    }
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    public String getEve() {
        return this.eve;
    }
    
    public void setEve(String eve) {
        this.eve = eve;
    }
    public String getStatust() {
        return this.statust;
    }
    
    public void setStatust(String statust) {
        this.statust = statust;
    }




}


