package entity;
// Generated Apr 30, 2018 11:35:56 PM by Hibernate Tools 4.3.1



/**
 * Perde generated by hbm2java
 */
public class Perde  implements java.io.Serializable {


     private Integer id;
     private int TId;
     private String name;
     private String BId;
     private String gender;
     private String email;
     private String con;
     private String fname;
     private String add;

    public Perde() {
    }

    public Perde(int TId, String name, String BId, String gender, String email, String con, String fname, String add) {
       this.TId = TId;
       this.name = name;
       this.BId = BId;
       this.gender = gender;
       this.email = email;
       this.con = con;
       this.fname = fname;
       this.add = add;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getTId() {
        return this.TId;
    }
    
    public void setTId(int TId) {
        this.TId = TId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBId() {
        return this.BId;
    }
    
    public void setBId(String BId) {
        this.BId = BId;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCon() {
        return this.con;
    }
    
    public void setCon(String con) {
        this.con = con;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getAdd() {
        return this.add;
    }
    
    public void setAdd(String add) {
        this.add = add;
    }




}


