package entity;
// Generated Apr 30, 2018 11:35:56 PM by Hibernate Tools 4.3.1



/**
 * Refer generated by hbm2java
 */
public class Refer  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String org;
     private String designa;
     private String mobile;
     private String email;

    public Refer() {
    }

    public Refer(String name, String org, String designa, String mobile, String email) {
       this.name = name;
       this.org = org;
       this.designa = designa;
       this.mobile = mobile;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getOrg() {
        return this.org;
    }
    
    public void setOrg(String org) {
        this.org = org;
    }
    public String getDesigna() {
        return this.designa;
    }
    
    public void setDesigna(String designa) {
        this.designa = designa;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


